### ISSUE TITLE
Add Modest maps

### ISSUE THREAD

**Issue by leossmith** [robinrodricks/awesome-actionscript3#1]
https://github.com/migurski/modestmaps-as3 

one of the few (if not the last one) Flex - as3 maps

**Comment by robinrodricks** [comment]
Thanks for this, but can you at least add a `README.md` with basic info on the API/Usage?

**Comment by leossmith** [comment]
Hi,

This is not mine so I can't add directly to it. I can make a rep with examples though.

**Comment by robinrodricks** [comment]
Can you fork it and add a readme with basic API or example code? But all examples should be INSIDE the readme.
