### ISSUE TITLE
What about intelliJ idea? 

### ISSUE THREAD

**Issue by syberkitten** [robinrodricks/awesome-actionscript3#10]
it's practically the best IDE you'll find out there
and it works seamlessly with all AIR SDKs.

**Comment by robinrodricks** [comment]
It's not usually used with AS3, plus the platform is dead anyways so idk.
Have any link where they sold project templates for AS3/SIR?

**Comment by ghost** [comment]
I've used IntelliJ IDEA for as3 for like 10 years or something. So I agree, it is pretty awesome for as3 dev. 
https://www.jetbrains.com/help/idea/building-actionscript-and-flex-applications.html

Still fighting the death! :D

**Comment by robinrodricks** [comment]
Added. Thanks.
