### ISSUE TITLE
Windebug ane

### ISSUE THREAD

**Issue by henke37** [robinrodricks/awesome-actionscript3#2]
http://www.henke37.cjb.net/windebug/

**Comment by robinrodricks** [comment]
Can you make a github repo for this? With a readme explaining the basic API? Or you could copy the reference manual into it...

**Comment by henke37** [comment]
This one I'm keeping closed source.

As for the explanation, anyone who is a good enough coder to be able to make use of it doesn't need a quickstart.

**Comment by robinrodricks** [comment]
Added. Thanks for your report!

I recommend making this open source so people can fix bugs and add features.
