### ISSUE TITLE
MotionParticleSprite

### ISSUE THREAD

**Issue by bjeld** [robinrodricks/awesome-actionscript3#3]
Mock up at motion path in Flash Pro and use it to guide a particle in your starling scene.

Blog Post (and download) -> http://bjeld.com/tools/get-creative-with-particles/
In Use Video recording -> https://vimeo.com/53717875

**Comment by robinrodricks** [comment]
Can you make a github repo for this? With a readme containing your "blog post" as well as some API docs?

**Comment by bjeld** [comment]
Sure, here you go -> https://github.com/bjeld/motionparticlesprite

**Comment by robinrodricks** [comment]
Added. Thanks for this!
