### ISSUE TITLE
Some ANEs for your consideration

### ISSUE THREAD

**Issue by tuarua** [robinrodricks/awesome-actionscript3#4]
WebViewANE 
WebView Adobe Air Native Extension for OSX 10.10+, Windows Desktop, iOS 9.0+ and Android 21+. This ANE provides access to a more modern webview from AIR. 
https://github.com/tuarua/WebViewANE

TaskbarProgressANE 
AIR Native Extension for displaying taskbar progress on OSX & Windows 7, 8, 10 
https://github.com/tuarua/TaskbarProgressANE

DesktopToastANE 
Adobe Air Native Extension for displaying adaptive and interactive toast notifications in Windows 8, 10 and OSX
https://github.com/tuarua/DesktopToastANE

BitTorrentANE 
Adobe Air Native Extension for building bittorrent enabled applications
https://github.com/tuarua/BitTorrentANE

AVANE 
Adobe Air Native Extension for building video encoding applications using FFmpeg
https://github.com/tuarua/AVANE

FreSharp 
C# wrapper for FlashRuntimeExtensions 
https://github.com/tuarua/FreSharp

Swift-IOS-ANE
FlashRuntimeExtensions.swift. Example Air Native Extension written in Swift 3 for iOS 10 
https://github.com/tuarua/Swift-IOS-ANE

**Comment by robinrodricks** [comment]
Amazing stuff! Thanks for submitting it. All are open source?

**Comment by robinrodricks** [comment]
- [WebViewANE](https://github.com/tuarua/WebViewANE) - Modern WebView for OSX 10.10+, Windows Desktop, iOS 9.0+ and Android 21+
- [TaskbarProgressANE](https://github.com/tuarua/TaskbarProgressANE) - Displaying taskbar progress on OSX & Windows 7, 8, 10 
- [DesktopToastANE](https://github.com/tuarua/DesktopToastANE) - Displaying interactive toast notifications in Windows 8, 10 and OSX
- [BitTorrentANE](https://github.com/tuarua/BitTorrentANE) - For building BitTorrent enabled applications
- [AVANE](https://github.com/tuarua/AVANE) - For building video encoding applications using FFmpeg
- [FreSharp](https://github.com/tuarua/FreSharp) - Build ANEs using C# with this C# wrapper for FlashRuntimeExtensions 
- [Swift-IOS-ANE](https://github.com/tuarua/Swift-IOS-ANE) - ANE starter kit written in Swift 3 for iOS 10

**Comment by tuarua** [comment]
Yes, all open source

**Comment by robinrodricks** [comment]
Really good job with all the projects. You have put a lot of hard work in there and it shows. Keep it up :)

**Comment by tuarua** [comment]
Thanks! I saw your ScintillaNET example. Looks interesting and something that could suit FreSharp to implement as a Windows ANE.

**Comment by robinrodricks** [comment]
Is it possible to integrate [CEFSharp](https://github.com/cefsharp/CefSharp) somehow via an ANE? Its a great chromium based browser for .NET exactly like Google Chrome. You can see a usage example [here](https://github.com/sharpbrowser/SharpBrowser).

**Comment by tuarua** [comment]
The first ANE on the list, WebViewANE, uses CEFSharp for the Windows version ;)

**Comment by robinrodricks** [comment]
Wow! Thats amazing!

**Comment by robinrodricks** [comment]
All ANEs added to the awesome list. Thanks again!
