### ISSUE TITLE
Pleas add Hockeyapp ANE

### ISSUE THREAD

**Issue by leossmith** [robinrodricks/awesome-actionscript3#8]
https://github.com/airext/hockeyapp

**Comment by robinrodricks** [comment]
Is hockeyapp FOSS?

**Comment by leossmith** [comment]
The ANE is open source, the service is free.

**Comment by robinrodricks** [comment]
What is it about?

**Comment by leossmith** [comment]
It is a testing / distribute platform just like Testflight was before apple bought it. 

https://hockeyapp.net/

**Comment by robinrodricks** [comment]
Done!
